// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: services.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessRequest_Authenticate_FullMethodName = "/pb.AccessRequest/Authenticate"
)

// AccessRequestClient is the client API for AccessRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// >> Document rpc...
type AccessRequestClient interface {
	Authenticate(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*AuthResponse, error)
}

type accessRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessRequestClient(cc grpc.ClientConnInterface) AccessRequestClient {
	return &accessRequestClient{cc}
}

func (c *accessRequestClient) Authenticate(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AccessRequest_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessRequestServer is the server API for AccessRequest service.
// All implementations must embed UnimplementedAccessRequestServer
// for forward compatibility.
//
// >> Document rpc...
type AccessRequestServer interface {
	Authenticate(context.Context, *Credentials) (*AuthResponse, error)
	mustEmbedUnimplementedAccessRequestServer()
}

// UnimplementedAccessRequestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessRequestServer struct{}

func (UnimplementedAccessRequestServer) Authenticate(context.Context, *Credentials) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAccessRequestServer) mustEmbedUnimplementedAccessRequestServer() {}
func (UnimplementedAccessRequestServer) testEmbeddedByValue()                       {}

// UnsafeAccessRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessRequestServer will
// result in compilation errors.
type UnsafeAccessRequestServer interface {
	mustEmbedUnimplementedAccessRequestServer()
}

func RegisterAccessRequestServer(s grpc.ServiceRegistrar, srv AccessRequestServer) {
	// If the following call pancis, it indicates UnimplementedAccessRequestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessRequest_ServiceDesc, srv)
}

func _AccessRequest_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessRequestServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessRequest_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessRequestServer).Authenticate(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessRequest_ServiceDesc is the grpc.ServiceDesc for AccessRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AccessRequest",
	HandlerType: (*AccessRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AccessRequest_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
