addr = "localhost:3333"
read_timeout = 30
write_timeout = 30
max_header_bytes = 1048576

# current user only postgres
[DBConfig]
host = "localhost"
port = 5432
username = "postgres"
password = "147563"
database = "database_report"
is_migratable = false

[Redis]
addr = "localhost:6379"
password = "your_password"
db = 0


