addr = "localhost:3335"

# current user only postgres
[DBConfig]
host = "localhost"
port = 5432
username = "postgres"
password = "147563"
database = "database_report"
is_migratable = false

[Redis]
addr = "localhost:6379"
password = "your_password"
db = 0


